name: tg-generator-bot
channels:
  - conda-forge
  - menpo
  - defaults
dependencies:
  - cachetools=5.3.*
  - diskcache=5.6.*
  - jinja2=3.1.*
  - pip=23.2.*
  - pip:
      - aiogram~=3.1.1
      - aiolimiter~=1.1.0
      - huggingface-hub~=0.17.3
      - python-dotenv~=1.0.0
      - torch~=2.1.0
      - transformers~=4.34.0
